### ISSUE TITLE
Should the language use persistent/immutable or mutable data structures?

### ISSUE THREAD

**Issue by walterpie** [gtk-ml/gtk-ml#11]
#10 Implemented some immutable/persistent data structures (later called IPDS) very similar to those present in Clojure. The basic semantics in gtk-ml would look like this:

```clojure
(define x [1 2 3 4 5]) ; creates a new array with the elements 1, 2, 3, 4 and 5 and assigns to 'x
(define y (push x 6)) ; creates a new array with all elements from x and adds 6 to the end and assigns to 'y,  without modifying x
(define z (concat y ["a string" :keyword])) ; creates a new array with all elements from y and concatenates with another array,  without modifying y
x ; evaluates to [1 2 3 4 5]
y ; evaluates to [1 2 3 4 5 6]
z ; evaluates to [1 2 3 4 5 6 "a string" :keyword]

(define m {:x 42 :y 54}) ; creates a new hash map :x -> 42, :y -> 54
(define n (insert m :z "henlo")) ; creates a new hash map with all elements from m and additionally inserts the key-value pair :z -> "henlo"
m ; = {:x 42 :y 54}
n ; = {:x 42 :y 54 :z "henlo"}

(define s #{1 3 5 7}) ; creates a new set with the keys 1, 3, 5, 7
(define t (insert s 9)) ; creates a new set from s with 9 an additional 9
s ; evaluates to #{1 3 5 7}
t ; evaluates to #{1 3 5 7 9}
```

Note that these operations are very efficient. They do not naively copy the entire contents, as if you allocated an array and `memcpy`d or deep-cloned its contents. All of these IPDSs are based on array-mapped tries (or hash array-mapped tries). Basically, every one of these data structures contains a pointer to a root node. Than that root node contains a pointer to more nodes. Every node may be a leaf node, containing an element or a key-value pair; or a node may also be a branch node containing a number (32 in the current implementation) of pointers to other nodes. Nodes are reference counted, rather than garbage collected, and may be shared by multiple other nodes. See the links below for a more in-depth explanation.

These persistent data structures have many upsides. IPDSs are nearly as efficient as non-persistent mutable ones. IPDSs can be used as keys in hash maps and hash sets, due to never changing (note that hash maps and sets either need the keys to be immutable, to copy the keys or simply need to "own" the keys [see Rust ownership model]). IPDSs fit nicely into the functional paradigm of Lisp.

Another note: mutability may still be present by borrowing Clojure's concept of variables. A variable is like a container with inner-mutability (think Rust's `Cell`, or `RefCell`). A variable may be bound to a local or global symbol and the value inside it can be swapped, without modifying any values. The only change is a swapping of the pointer inside of a variable. The semantics would look something like this:

```clojure
(define x (var 0))
(assign x (+ (get x) 1))
;; or to be slightly more concise
(assign x (+ @x 1))
```

Where `@` is a reader macro (see #5, c3ad22c) that evaluates to `(get x)`.

Another option would be to ditch immutability and make the structures mutable, like in Lua and go for more Lua-like semantics, rather than Clojure/Haskell like semantics.

Links:

[Understanding Clojure's persistent vector](https://hypirion.com/musings/understanding-persistent-vector-pt-1)  
[Understandings Clojure's PersistentHashMap](https://blog.higher-order.net/2009/09/08/understanding-clojures-persistenthashmap-deftwice.html)  
[Clojure docs: clojure.core/var](https://clojuredocs.org/clojure.core/var)  
[Wikipedia: Hash Array Mapped Trie](https://en.wikipedia.org/wiki/Hash_array_mapped_trie)  
[Wikipedia: Lua#Tables](https://en.wikipedia.org/wiki/Lua_(programming_language)#Tables)  
[The implementation of Lua 5.0](https://www.lua.org/doc/jucs05.pdf)

**Comment by walterpie** [comment]
@fneddy, please comment

**Comment by walterpie** [comment]
Obviously, since I implemented these IPDSs, I'd prefer if we used them.

**Comment by fneddy** [comment]
I like the concept of immutable data structures. through i have some questions:

will we support pointer/references in gtk-ml? if so what would happen to a ref if i reassign the original IPDS?

```lisp
(define x [0 1 2 3])

(call function &x)

(assign x (+ @x 4)

; what will happen to the passed x?
```

easiest would be to now have ref or pointer types at all in the lang. But this will create problems when we need shared data between gtk-ml and its host (c).

**Comment by walterpie** [comment]
Vars already work like safe pointers/references. If a value is represented as `GtkMl_S *`, then a var acts like a `GtkMl_S **`.

**Comment by walterpie** [comment]
Or to represent the semantics better, a value is a `const GtkMl_S *` (the value inside the pointer cannot be modified and a var is a `const GtkMl_S **`. The underlying value still can't be modified, but now the pointer to the value can be modified.
