### ISSUE TITLE
How should user defined types be implemented?

### ISSUE THREAD

**Issue by walterpie** [gtk-ml/gtk-ml#12]
There are multiple options for this. I'm gonna list them and some pros and cons.

1. Java-like classes/structures. Every type is a class. Instances of classes are called objects/structures. Classes are also objects, or instances of the class `Class`.  
Pros: Allows certain optimizations to be performed.  
Cons: honestly, too many to list. I'm not a fan of Java :rofl:. But this is still a valid user-define type implementation.  
For example a `BasicBlock` type might be implemented like this in Java:
```java
public class BasicBlock {
    public String name;
    public ArrayList<Instruction> instructions;

    BasicBlock(String name, ArrayList<Instruction> instructions) {
        this.name = name;
        this.instructions = instructions;
    }

    void some_method() {
        System.out.println("Inside some method");
    }

    static void some_function() {
        System.out.println("Inside some static function");
    }
}

public class Main {
    public static void main(String[] args) {
        BasicBlock bb = BasicBlock("main", new ArrayList<Instructions>());
        bb.some_method();
        BasicBlock.some_function();
    }
}
```
Or in gtk-ml:
```clojure
(class BasicBlock
  [name
   instructions]
  (cons (BasicBlock name instructions)
    (assign (.this name) name)
    (assign (.this instructions) instructions))
  (method (some_method)
    (println "Inside some method"))
  (define (some_function)
    (println "Inside some static function")))

(define bb (BasicBlock "main" []))
(.bb some_method)
(.BasicBlock some_function)
```
2. Lua-like tables/metatables. The only types that exist are the ~22 builtin types. Users can define new types by creating tables with metatables. Every table contains a metatable. A metatable is also a table. A user-defined type is simply a certain table-structure, enforced by a "constructor" function. A similar approach is also used by Clojure.  
Pros: very lightweight. We already have everything we need for this implementation.  
Cons: certain optimizations cannot be performed with table-based structures. (Or can they?)  
For example a `BasicBlock` type might be implemented like this in Lua:
```lua
function BasicBlock(name, instructions)
    if type(name) != "string"
        return nil
    end
    if type(instructions) != "table"
        return nil
    end
    return {name = name, instructions = instructions}
end
```
Or in gtk-ml:
```clojure
(define (BasicBlock name instructions)
  (cond
    (/= (type name) "string") #nil
    (/= (type instructions) "map") #nil
    :else {:name name :instructions instructions}))
```
3. JavaScript-like functions/metatables. The only types that exist are the ~22 builtin types. Users can define new types by creating functions with metatables. Every function contains a metatable. A metatable is also a table. A user-defined type is simply a certain table-structure, enforced by a type function. For example a `BasicBlock` type might be implemented like this in JavaScript:
Pros/cons: same as 2.
```javascript
function BasicBlock(name, instructions) {
    this.name = name;
    this.instructions = instructions;
}
```
Or in gtk-ml:
```clojure
(define (BasicBlock name instructions)
  (assign (.this name) name) ; gets the name property from .this (which is a var [see #11 paragraph on vars]) and assigns to it the value of name
  (assign (.this instructions) instructions))  ; gets the instructions property from .this (which is a var [see #11 paragraph on vars]) and assigns to it the value of instructions
```
4. Haskell-like ADTs (algebraic data types). Users can define new types. Every type may have multiple constructors. If type `Struct` was instantiated with a constructor `A`, it's only able to use the fields defined on `A`.  
Pros: certain optimizations can be performed; ADTs, baby! A single concept implements both structs and enums.  
Cons: not as lightweight as 2. or 3; would (probably?) require copying the whole structure on modification, because immutability.  
For example a `BasicBlock` type might be implemented like this in Haskell:
```haskell
data BasicBlock =
    NamedBb name instructions
  | AnonymousBb instructions
-- late
NamedBb "main" []
```
Or in gtk-ml:
```clojure
(data BasicBlock
  (cons (NamedBb name instructions))
  (cons (AnonymousBb instructions)))
; later
(NamedBB "main" [])
```
5. C/Rust-like structs, unions and enums. Users can define new types of different kinds. Constructors do not exist, but constructing functions can be defined separately.  
Pros: certain optimizations can be performed; this is the lowest-level approach, giving the most power; relatively simple to implement.  
Cons: The lowest-level approach, requiring the most input from the programmer; doesn't fit nicely into the functional paradigm of Lisp; would (probably?) require copying the whole structure on modification, because immutability.  
For example a BasicBlock might be implemented like this in C:
```c
struct BasicBlock {
    const char *name;
    Instruction *instructions;
    size_t len_instructions;
    size_t cap_instructions;
};
```
Or in gtk-ml:
```clojure
(struct BasicBlock
  [name instructions])
```

These approaches can be mixed. The high-level semantics and low-level implementation might use different approaches. For example the language-level semantics might use 4., but internally be implemented as 2. or 3.

**Comment by walterpie** [comment]
@fneddy, please comment

**Comment by walterpie** [comment]
I'd be most happy with the second approach. It fits nicely into what we already have and is very lightweight.

**Comment by walterpie** [comment]
The Lua approach is also extremely flexible an makes it extremely simple to implement overloading and operator overloading later on.

**Comment by fneddy** [comment]
i agree with you the lua approach also seems to me the nicest one.

**Comment by walterpie** [comment]
Lua tables it is.
